### ISSUE TITLE
A developer should be able to checkout the project and know what to do

### ISSUE THREAD

**Issue by Turbots** [oraj-360/oraj360tool#15]
If we want to make the development on the 360 tool as smooth as possible, developers should be able to check out the project and start immediately. Streamline the development process!

**Comment by yannickdeturck** [comment]
Cloning the project, importing it and getting it running via Multirun in IntelliJ already appears to be well documented. Only the part about getting it running in Eclipse is missing and I think it would be a good idea to describe the most common Git workflows (pull rebase before pushing, be sure to push updated references in the parent project, etc) in order to have a little cheat sheet for developing.

**Comment by Turbots** [comment]
@HPacquee can you add a small tutorial on how to setup the tool using Eclipse or STS?
@TYsewyn can you add a section on how to properly commit the parent / submodules with Git? Maybe a small tutorial using Github Desktop with screenshots?

**Comment by HPacquee** [comment]
@Turbots it's partly done but needs testing still, I'll try to get it done asap
